version: '3.7'
services:
  mongo:
      image: mongo
      restart: always
      networks:
        - my-net
      environment:
        MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
        MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ports:
        - 27017:27017

networks:
  my-net:
    driver: bridge